## Settings
title: 猪猪屋-一个我的记录财富的地方
owner: "Zhusong"
url: "https://www.lasong.com.cn"
baseurl: ""
permalink: /:title/
description: "Blog By Zhusong"
markdown: kramdown
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
plugins:
  - jekyll-sitemap
## Global Variables
email: "song.zhu@lasong.com.cn"
github: "zhusonger/"
# path to: css/, fonts/, img/ and js/
assets_path: "/assets" # i.e. "/assets" 
statement: "Zhusong, All Rights Reserved"
aq: "浙ICP备20003389号-1"
aqlink: "http://beian.miit.gov.cn"
# default max toc levels: 1 - 6 (h1 - h6)
toc_level: 3
# texts randomly displayed in background
bgtext: "αβγδεζηθικλμνξοπρστυφχψω∷∫∮∝∞∧∨∑∏∪∩∈∵∴⊥‖∠⌒⊙≌√"
