## Settings
title: 猪猪屋
owner: "Zhusong"
url: "https://www.lasong.com.cn"
baseurl: ""
permalink: /:title/
description: ""
markdown: kramdown
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
## Global Variables
email: "song.zhu@lasong.com.cn"
github: "zhusonger/zhusonger.github.io"
# path to: css/, fonts/, img/ and js/
assets_path: "/assets" # i.e. "/assets" 
statement: "Zhusong, All Rights Reserved"
aq: "浙ICP备20003389号-1"
# default max toc levels: 1 - 6 (h1 - h6)
toc_level: 3
# texts randomly displayed in background
bgtext: "αβγδεζηθικλμνξοπρστυφχψω∷∫∮∝∞∧∨∑∏∪∩∈∵∴⊥‖∠⌒⊙≌√"